name: action1
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $GITHUB_RUN_NUMBER >> index.html
      - run: ls -ltr
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: tvdvoorde
          password: ${{ secrets.DOCKERPW }}
      - run: docker build . -t tvdvoorde/sample:$GITHUB_RUN_NUMBER
      - run: docker push tvdvoorde/sample:$GITHUB_RUN_NUMBER
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.CREDENTIALS }}
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        id: deploy
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION }}
          resourceGroupName: rggithubtest
          template: ./arm/aci.json
          parameters: name=githubtest image=tvdvoorde/sample:${{ github.run_number }}
      - run: echo ${{ steps.deploy.outputs.containerIPv4Address }}


