name: action1
on: [push]
jobs:
  basicinfo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: printenv
      - run: ls -ltr
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: tvdvoorde
          password: ${{ secrets.DOCKERPW }}
      
