name: action1
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: printenv
      - run: ls -ltr
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: tvdvoorde
          password: ${{ secrets.DOCKERPW }}
      - run: docker build . -t tvdvoorde/sample:latest
      - run: docker push tvdvoorde/sample:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: printenv    
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.CREDENTIALS }}
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION }}
          resourceGroupName: rggithubtest
          template: ./arm/aci.json
          parameters: name=githubtest4 image=tvdvoorde/sample:latest
          


