name: action1
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: printenv
      - run: ls -ltr
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: tvdvoorde
          password: ${{ secrets.DOCKERPW }}
      - run: docker build . -t tvdvoorde/sample:$GITHUB_RUN_NUMBER
      - run: docker push tvdvoorde/sample:$GITHUB_RUN_NUMBER
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: printenv    
